# Generated by Django 4.2.6 on 2023-10-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_flight_duration_alter_flight_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='duration',
        ),
    ]
